import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 0,
  },
  header: {
    backgroundColor: '#1a1a2e',
    paddingTop: 40,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 15,
    backgroundColor: '#1a1a2e',
  },
  headerButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginHorizontal: 5,
    backgroundColor: '#6366f1',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#6366f1',
    elevation: 5,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
  },
  headerButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
  },
  gameTitleContainer: {
    backgroundColor: '#ef4444',
    paddingVertical: 15,
    marginHorizontal: 15,
    marginBottom: 10,
    borderRadius: 15,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    borderWidth: 2,
    borderColor: '#dc2626',
  },
  gameTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 2,
    textShadowOffset: { width: 2, height: 2 },
    textShadowOpacity: 0.8,
  },
  headerInfo: {
    flexDirection: 'row',
    backgroundColor: '#6366f1',
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginHorizontal: 15,
    marginBottom: 15,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#6366f1',
    elevation: 5,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
  },
  headerInfoColumn: {
    flex: 1,
  },
  headerInfoItem: {
    alignItems: 'center',
  },
  infoLabel: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 4,
    marginBottom: 2,
  },
  timeText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  tokenText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Enhanced Session Styles with Animations
  sessionsContainer: {
    padding: 15,
    gap: 15,
  },
  sessionCard: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    borderWidth: 3,
    borderColor: '#e5e7eb',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    transform: [{ perspective: 1000 }],
  },
  selectedSessionCard: {
    backgroundColor: '#ff6b35',
    borderColor: '#ff6b35',
    elevation: 12,
    shadowColor: '#ff6b35',
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  disabledSessionCard: {
    opacity: 0.5,
  },
  sessionLabel: {
    color: '#374151',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  sessionTime: {
    color: '#6b7280',
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 8,
    fontWeight: 'bold',
  },
  countdownText: {
    color: 'black',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  selectedSessionText: {
    color: 'white',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  selectedCountdownText: {
    color: '#fef3c7',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  // Enhanced Choice Mode Styles with Animations
  choiceModeContainer: {
    padding: 15,
    gap: 12,
  },
  choiceModeButton: {
    backgroundColor: 'white',
    paddingVertical: 18,
    paddingHorizontal: 25,
    borderRadius: 30,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#e5e7eb',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    transform: [{ perspective: 1000 }],
  },
  selectedChoiceModeButton: {
    backgroundColor: '#ff6b35',
    borderColor: '#ff6b35',
    elevation: 10,
    shadowColor: '#ff6b35',
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  disabledChoiceModeButton: {
    opacity: 0.3,
  },
  choiceModeButtonText: {
    color: '#374151',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  selectedChoiceModeButtonText: {
    color: 'white',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  // Enhanced Image Grid Styles with Animations
  imageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 15,
    justifyContent: 'space-between',
    gap: 20,
  },
  imageButton: {
    width: (width - 70) / 2,
    height: (width - 70) / 2,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    marginBottom: 20,
    borderWidth: 3,
    borderColor: '#e2e8f0',
    transform: [{ perspective: 1000 }],
  },
  selectedImageButton: {
    borderColor: '#4ade80',
    borderWidth: 4,
    elevation: 15,
    shadowColor: '#4ade80',
    shadowOpacity: 0.5,
  },
  selectedImageOverlay: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 20,
    padding: 5,
    elevation: 5,
    shadowColor: '#4ade80',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  imageStyle: {
    width: '100%',
    height: '100%',
    borderRadius: 17,
  },
  // Enhanced Selected Images Styles with Animations
  selectedImagesContainer: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    margin: 15,
    borderRadius: 25,
    padding: 25,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#ff6b35',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    borderWidth: 3,
    borderColor: '#f3f4f6',
  },
  selectedImagesTitle: {
    color: '#1f2937',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  fixedSelectedImagesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '120%',
    paddingHorizontal: 10,
  },
  selectedImageSlot: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 8,
  },
  selectedImageItem: {
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 15,
    elevation: 8,
    shadowColor: '#ff6b35',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    width: '100%',
  },
  // NEW STYLES FOR X BUTTON
  selectedImageWrapper: {
    position: 'relative',
    alignItems: 'center',
  },
  selectedImage: {
    width: 80,
    height: 80,
    borderRadius: 15,
    backgroundColor: 'white',
  },
  removeIconButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#ef4444',
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  // REMOVED OLD REMOVE BUTTON STYLES
  emptyImageSlot: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f9fafb',
    borderRadius: 20,
    padding: 15,
    borderWidth: 3,
    borderColor: '#e5e7eb',
    borderStyle: 'dashed',
    width: '100%',
    height: 130,
  },
  emptySlotText: {
    color: '#9ca3af',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  
  // Enhanced Bet Section with Animations
  betSectionContainer: {
    backgroundColor: '#4f46e5',
    marginHorizontal: 15,
    marginTop: 25,
    borderRadius: 25,
    padding: 25,
    elevation: 15,
    shadowColor: '#4f46e5',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    borderWidth: 3,
    borderColor: '#4338ca',
  },
  
  betInputContainer: {
    marginBottom: 20,
  },
  
  betInput: {
    backgroundColor: 'white',
    borderRadius: 20,
    paddingHorizontal: 25,
    paddingVertical: 20,
    fontSize: 18,
    color: '#1f2937',
    fontWeight: '700',
    textAlign: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    borderWidth: 3,
    borderColor: '#e5e7eb',
  },
  
  placeBetButtonContainer: {
    width: '100%',
  },
  
  placeBetButton: {
    backgroundColor: '#ef4444',
    paddingVertical: 22,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    borderWidth: 3,
    borderColor: '#dc2626',
    minHeight: 65,
  },
  
  disabledPlaceBetButton: {
    backgroundColor: '#9ca3af',
    borderColor: '#6b7280',
    elevation: 5,
  },
  
  placeBetButtonText: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },

  bottomSpacer: {
    height: 100,
    backgroundColor: 'transparent',
  },
  
  // Enhanced Modal Styles with Animations
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 30,
    borderRadius: 25,
    margin: 20,
    maxWidth: width * 0.85,
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    borderWidth: 2,
    borderColor: '#f3f4f6',
    alignItems: 'center',
  },
  modalIconContainer: {
    marginBottom: 15,
    padding: 10,
    borderRadius: 50,
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  modalText: {
    fontSize: 18,
    textAlign: 'center',
    color: '#333',
    fontWeight: '600',
    lineHeight: 24,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  modalErrorText: {
    color: '#ef4444',
  },
  modalSuccessText: {
    color: '#10b981',
  },
  modalWarningText: {
    color: '#f59e0b',
  },
  titleDivider: {
  height: 1.5,
  backgroundColor: 'rgba(255, 255, 255, 0.4)',
  marginTop: 12,
  marginBottom: 15,
},

});

export default styles;