import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#EBF4FF',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  contentWrapper: {
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
    marginTop:30
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    color: '#4B5563',
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
  },
  kycIntro: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 32,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  kycIntroContent: {
    alignItems: 'center',
  },
  kycIntroTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
    marginTop: 16,
    marginBottom: 12,
    textAlign: 'center',
  },
  kycIntroText: {
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  startKycBtn: {
    backgroundColor: '#4F46E5',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: '#4F46E5',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  startKycBtnText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  kycForm: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 32,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  kycTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
    textAlign: 'center',
    marginBottom: 8,
  },
  kycSubtitle: {
    color: '#6B7280',
    textAlign: 'center',
    fontSize: 14,
    marginBottom: 32,
  },
  documentUpload: {
    marginBottom: 24,
  },
  documentLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  documentLabelText: {
    fontWeight: '600',
    color: '#374151',
    marginLeft: 8,
    fontSize: 16,
  },
  optionalText: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '400',
  },
  uploadArea: {
    borderWidth: 2,
    borderColor: '#D1D5DB',
    borderStyle: 'dashed',
    borderRadius: 16,
    padding: 24,
    backgroundColor: '#F9FAFB',
    minHeight: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadProgress: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  uploadProgressText: {
    color: '#4F46E5',
    fontWeight: '500',
    marginLeft: 8,
  },
  uploadSuccess: {
    alignItems: 'center',
    width: '100%',
  },
  uploadSuccessText: {
    color: '#059669',
    fontWeight: '500',
    marginLeft: 8,
    textAlign: 'center',
    marginTop: 8,
  },
  previewImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginTop: 8,
  },
  uploadPlaceholder: {
    alignItems: 'center',
  },
  uploadPlaceholderText: {
    color: '#6B7280',
    marginTop: 8,
    textAlign: 'center',
  },
  errorText: {
    color: '#DC2626',
    fontSize: 12,
    marginTop: 8,
  },
  
  // PAN Number Input Styles
  panInputContainer: {
    width: '100%',
  },
  panInput: {
    width: '100%',
    padding: 16,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    fontSize: 16,
    fontWeight: '600',
    textTransform: 'uppercase',
    textAlign: 'center',
    backgroundColor: 'white',
    letterSpacing: 1,
    color:"black"
  },
  panInputError: {
    borderColor: '#DC2626',
  },
  panCheckingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  panCheckingText: {
    color: '#4F46E5',
    fontSize: 13,
    marginLeft: 6,
  },
  panAvailableContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  panAvailableText: {
    color: '#059669',
    fontSize: 13,
    marginLeft: 6,
  },
  panFormatText: {
    color: '#6B7280',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 8,
  },
  
  // Selfie Specific Styles
  selfieSection: {
    marginBottom: 24,
  },
  selfieArea: {
    borderWidth: 3,
    borderColor: '#4F46E5',
    borderStyle: 'dashed',
    borderRadius: 20,
    padding: 28,
    backgroundColor: '#F8F9FF',
    minHeight: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selfiePlaceholder: {
    alignItems: 'center',
  },
  selfiePlaceholderTitle: {
    color: '#4F46E5',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 8,
  },
  selfiePlaceholderText: {
    color: '#6B7280',
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
  },
  selfieSuccess: {
    alignItems: 'center',
    width: '100%',
  },
  selfiePreviewThumb: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginTop: 12,
    marginBottom: 12,
    borderWidth: 3,
    borderColor: '#059669',
  },
  retakeSmallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginTop: 8,
  },
  retakeSmallText: {
    color: '#4F46E5',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 4,
  },
  
  // Selfie Preview Modal Styles
  selfiePreviewModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
  },
  selfiePreviewContainer: {
    flex: 1,
    justifyContent: 'space-between',
  },
  selfiePreviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
    paddingBottom: 20,
  },
  selfiePreviewCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop:50
  },
  selfiePreviewTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
    marginTop:50
  },
  selfieImageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  selfiePreviewImage: {
    width: width * 0.8,
    height: width * 0.8,
    borderRadius: width * 0.4,
    borderWidth: 4,
    borderColor: 'white',
  },
  selfiePreviewActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: 40,
    paddingBottom: 80,
    paddingTop: 20,
    gap:10
  },
  retakeSelfieBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6B7280',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 25,
    minWidth: 120,
    justifyContent: 'center',
  },
  retakeSelfieText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  confirmSelfieBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#059669',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 25,
    minWidth: 120,
    justifyContent: 'center',
  },
  confirmSelfieText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  
  submitKycBtn: {
    backgroundColor: '#059669',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 16,
    shadowColor: '#059669',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  submitKycBtnDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
    elevation: 0,
  },
  submitKycBtnText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  accountCreation: {
    alignItems: 'center',
  },
  kycSuccess: {
    backgroundColor: '#ECFDF5',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  kycSuccessTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#065F46',
    marginTop: 16,
    marginBottom: 12,
    textAlign: 'center',
  },
  kycSuccessText: {
    color: '#047857',
    textAlign: 'center',
    lineHeight: 22,
  },
  createAccountBtn: {
    backgroundColor: '#2563EB',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 16,
    shadowColor: '#2563EB',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  createAccountBtnDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
    elevation: 0,
  },
  createAccountBtnText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(17, 24, 39, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 24,
    maxWidth: 500,
    width: '100%',
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 25,
    },
    shadowOpacity: 0.25,
    shadowRadius: 50,
    elevation: 25,
  },
  verificationHeader: {
    padding: 32,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: 'white',
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 16,
    color: 'white',
    textAlign: 'center',
    opacity: 0.95,
  },
  verificationContent: {
    padding: 32,
  },
  
  // User ID Box Styles
  userIdBox: {
    backgroundColor: '#f8fffe',
    borderRadius: 18,
    padding: 28,
    marginBottom: 20,
    borderWidth: 3,
    borderColor: '#28a745',
  },
  userIdHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  userIdTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#155724',
    marginLeft: 12,
  },
  
  // Referral ID Box Styles
  referralIdBox: {
    backgroundColor: '#fff8e1',
    borderRadius: 18,
    padding: 28,
    marginBottom: 32,
    borderWidth: 3,
    borderColor: '#ffc107',
  },
  referralIdHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  referralIdTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#856404',
    marginLeft: 12,
  },
  
  // Common ID Display Styles
  idDisplayContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  userIdDisplay: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e9ecef',
    marginRight: 12,
  },
  referralIdDisplay: {
    flex: 1,
    backgroundColor: '#fffdf6',
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ffeaa7',
    marginRight: 12,
  },
  userIdText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
    letterSpacing: 1,
  },
  referralIdText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#856404',
    textAlign: 'center',
    letterSpacing: 1,
  },
  copyButton: {
    backgroundColor: '#007bff',
    borderRadius: 12,
    padding: 14,
    minWidth: 80,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  copyButtonSuccess: {
    backgroundColor: '#28a745',
  },
  copyButtonText: {
    color: 'white',
    fontSize: 12,
    marginLeft: 4,
    fontWeight: '500',
  },
  userIdNote: {
    fontSize: 14,
    color: '#6c757d',
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 20,
  },
  referralIdNote: {
    fontSize: 14,
    color: '#856404',
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 20,
  },
  
  verificationStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff3cd',
    padding: 18,
    borderRadius: 50,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: '#ffeaa7',
  },
  verificationStatusText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#856404',
    marginLeft: 14,
  },
  timeline: {
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    padding: 24,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  timelineText: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 18,
    flex: 1,
  },
  importantNote: {
    backgroundColor: '#e7f3ff',
    borderRadius: 18,
    padding: 28,
    marginBottom: 32,
    borderWidth: 2,
    borderColor: '#b3d7ff',
  },
  importantNoteTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0056b3',
    marginBottom: 20,
    textAlign: 'center',
  },
  importantNoteText: {
    fontSize: 15,
    color: '#495057',
    lineHeight: 24,
    textAlign: 'left',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 18,
  },
  loginBtn: {
    flex: 1,
    backgroundColor: '#007bff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 14,
    shadowColor: '#007bff',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 5,
  },
  loginBtnText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
    textAlign: 'center',
  },
  helpBtn: {
    flex: 1,
    backgroundColor: '#6c757d',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 14,
    shadowColor: '#6c757d',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 5,
  },
  helpBtnText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
    textAlign: 'center',
  },
  alertContainer: {
    position: 'absolute',
    top: 50,
    left: 16,
    right: 16,
    zIndex: 1001,
    alignItems: 'center',
  },
  alert: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 10,
    maxWidth: 400,
  },
  alertSuccess: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  alertError: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  alertText: {
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 12,
    flex: 1,
  },
  alertTextSuccess: {
    color: '#047857',
  },
  alertTextError: {
    color: '#dc2626',
  },
  importantNotice: {
    backgroundColor: '#fff3cd',
    borderWidth: 2,
    borderColor: '#ffeaa7',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    shadowColor: '#ffc107',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  importantNoticeContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  importantNoticeIcon: {
    flexShrink: 0,
    marginTop: 2,
  },
  importantNoticeTextContainer: {
    flex: 1,
  },
  importantNoticeTitle: {
    color: '#856404',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  importantNoticeText: {
    color: '#856404',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
  },
});

export default styles;